// src/lib/components/tracker/PokemonSearch.svelte
<script lang="ts">
	import type { PokemonDetail } from '$lib/types';
	import { ribbonProgress } from '$lib/stores/ribbonProgress.svelte';
	import { normalizeForSearch } from '$lib/utils/searchNormalize';

	/** Props */
	let { allPokemon }: { allPokemon: PokemonDetail[] } = $props();

	/** 検索クエリ */
	let searchQuery = $state('');

	/** 検索結果（最大20件） */
	const MAX_RESULTS = 20;

	const results = $derived(
		(() => {
			const query = normalizeForSearch(searchQuery.trim());
			if (!query) return [];
			return allPokemon
				.filter((p) => normalizeForSearch(p.name).includes(query))
				.slice(0, MAX_RESULTS);
		})()
	);

	const SEARCH_INPUT_ID = 'pokemon-search-input';

	/** ポケモンを選択する */
	function selectPokemon(pokemon: PokemonDetail): void {
		ribbonProgress.selectPokemon(pokemon);
		searchQuery = '';
	}

	/** 図鑑番号を3桁ゼロ埋みでフォーマットする */
	function formatDexNumber(n: number): string {
		return String(n).padStart(3, '0');
	}
</script>

<div class="rounded-lg bg-white p-2 shadow md:p-4">
	<div class="mb-2 md:mb-4">
		<label for={SEARCH_INPUT_ID} class="mb-1 block text-xs font-bold text-gray-700 md:mb-2">
			ポケモンを検索
		</label>
		<div class="relative">
			<input
				id={SEARCH_INPUT_ID}
				type="text"
				bind:value={searchQuery}
				placeholder="ピカチュウ、フシギダネなど..."
				class="w-full rounded-lg border px-3 py-1.5 text-sm md:px-4 md:py-2 md:text-base"
			/>
		</div>
	</div>

	<!-- 検索結果リスト -->
	{#if results.length > 0}
		<div class="mt-2 max-h-60 overflow-y-auto md:max-h-80">
			{#each results as pokemon (pokemon.id)}
				<button
					class="flex w-full items-center rounded p-2 text-left hover:bg-gray-100"
					onclick={() => selectPokemon(pokemon)}
				>
					<!-- サムネイル -->
					<div class="mr-3 h-10 w-10 shrink-0">
						{#if pokemon.image}
							<img src={pokemon.image} alt={pokemon.name} class="h-full w-full object-contain" />
						{:else}
							<div class="h-full w-full rounded-full bg-gray-200"></div>
						{/if}
					</div>
					<!-- 名前・図鑑番号 -->
					<div>
						<div class="text-sm font-medium">{pokemon.name}</div>
						<div class="text-xs text-gray-500">#{formatDexNumber(pokemon.dexNumber)}</div>
					</div>
				</button>
			{/each}
		</div>
	{:else if searchQuery.trim()}
		<div class="py-4 text-center">
			<p class="text-gray-500">ポケモンが見つかりません</p>
			<p class="text-sm text-gray-400">別の名前で検索してください</p>
		</div>
	{/if}
</div>

// components/PokemonSearch.vue
<template>
  <div class="pokemon-search p-2 md:p-4 bg-white rounded-lg shadow">
    <div class="mb-2 md:mb-4">
      <label class="block text-gray-700 text-xs md:text-sm font-bold mb-1 md:mb-2"> ポケモンを検索してね～💖 </label>
      <div class="relative">
        <input
          v-model="searchQuery"
          type="text"
          class="w-full px-3 py-1.5 md:px-4 md:py-2 border rounded-lg text-sm md:text-base"
          placeholder="ピカチュウ、ヒトカゲなど..."
        />
      </div>
    </div>

    <!-- 検索結果表示 -->
    <div v-if="results.length > 0" class="mt-2 max-h-60 md:max-h-80 overflow-y-auto">
      <div
        v-for="pokemon in results"
        :key="pokemon.id"
        class="flex items-center p-2 hover:bg-gray-100 rounded cursor-pointer"
        @click="selectPokemon(pokemon)"
      >
        <div class="w-10 h-10 mr-3">
          <img
            v-if="pokemon.imageUrl"
            :src="pokemon.imageUrl"
            :alt="pokemon.name"
            class="w-full h-full object-contain"
          />
          <div v-else class="w-full h-full bg-gray-200 rounded-full"></div>
        </div>
        <div>
          <div class="font-medium">{{ pokemon.name }}</div>
          <div class="text-xs text-gray-500">{{ pokemon.number }}</div>
        </div>
      </div>
    </div>

    <div v-else-if="searchQuery" class="text-center py-4">
      <p class="text-gray-500">ポケモンが見つからないよ～😢</p>
      <p class="text-sm text-gray-400">別の名前で検索してみてね！</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { toPokemon } from '~/utils/pokemonMapper';
import type { Pokemon, PokemonDetail } from '~/types';

const props = defineProps<{
  allPokemon: PokemonDetail[];
  selectedPokemon: Pokemon | null;
}>();

const emit = defineEmits<{
  (e: 'select-pokemon', pokemon: Pokemon): void;
}>();

const searchQuery = ref('');

/** 検索クエリに一致するポケモンをフィルタリング */
const results = computed<Pokemon[]>(() => {
  const query = searchQuery.value.trim();
  if (!query) return [];
  return props.allPokemon.filter((p) => p.name.includes(query)).map(toPokemon);
});

/** ポケモン選択: 親に emit して検索欄をクリア */
const selectPokemon = (pokemon: Pokemon): void => {
  emit('select-pokemon', pokemon);
  searchQuery.value = '';
};
</script>
