// src/lib/components/tracker/PokemonDetails.svelte
<script lang="ts">
	import { ribbonProgress } from '$lib/stores/ribbonProgress.svelte';
	import { getGameName } from '$lib/utils/gameNames';

	/** タイプ別Tailwindクラスマッピング（18タイプ対応） */
	const TYPE_CLASSES: Record<string, string> = {
		ノーマル: 'bg-gray-400',
		ほのお: 'bg-orange-500',
		みず: 'bg-blue-500',
		でんき: 'bg-yellow-400',
		くさ: 'bg-green-500',
		こおり: 'bg-cyan-300',
		かくとう: 'bg-red-700',
		どく: 'bg-purple-500',
		じめん: 'bg-yellow-700',
		ひこう: 'bg-blue-400',
		エスパー: 'bg-pink-400',
		むし: 'bg-lime-500',
		いわ: 'bg-yellow-600',
		ゴースト: 'bg-purple-700',
		ドラゴン: 'bg-indigo-600',
		あく: 'bg-gray-700',
		はがね: 'bg-gray-500',
		フェアリー: 'bg-pink-300'
	};

	/** タイプ名からTailwindクラスを取得する */
	function getTypeClass(type: string): string {
		return TYPE_CLASSES[type] ?? 'bg-gray-400';
	}

	/** リボン獲得率を計算する */
	const ribbonPercentage = $derived(
		ribbonProgress.allRibbons.length === 0
			? 0
			: Math.round(
					(ribbonProgress.currentCheckedRibbons.length / ribbonProgress.allRibbons.length) * 100
				)
	);
</script>

{#if ribbonProgress.selectedPokemon}
	{@const pokemon = ribbonProgress.selectedPokemon}
	<div class="rounded-lg bg-white p-2 shadow md:p-4">
		<!-- ポケモン基本情報 -->
		<div class="mb-2 flex items-center md:mb-4">
			<div class="mr-2 md:mr-4">
				{#if pokemon.image}
					<img
						src={pokemon.image}
						alt={pokemon.name}
						class="h-16 w-16 object-contain md:h-24 md:w-24"
					/>
				{:else}
					<div class="h-16 w-16 rounded-full bg-gray-200 md:h-24 md:w-24"></div>
				{/if}
			</div>

			<div>
				<h2 class="text-lg font-bold md:text-xl">{pokemon.name}</h2>
				<p class="text-gray-600">
					#{String(pokemon.dexNumber).padStart(3, '0')}
				</p>
				<!-- タイプバッジ -->
				<div class="mt-1 flex gap-1 md:gap-2">
					{#each pokemon.types as type (type)}
						<span class="rounded px-2 py-1 text-xs text-white {getTypeClass(type)}">
							{type}
						</span>
					{/each}
				</div>
			</div>
		</div>

		<!-- マイポケモン追加情報 -->
		{#if ribbonProgress.activeMyPokemon}
			{@const mp = ribbonProgress.activeMyPokemon}
			<div class="mt-2 rounded-lg bg-blue-50 p-2 md:mt-3 md:p-3">
				<div class="flex flex-wrap gap-2 text-sm">
					{#if mp.nickname}
						<span class="inline-flex items-center gap-1">
							<span class="text-gray-500">NN:</span>
							<span class="font-medium">{mp.nickname}</span>
						</span>
					{/if}
					{#if mp.originGame}
						<span class="inline-flex items-center gap-1">
							<span class="text-gray-500">出身:</span>
							<span class="font-medium">{getGameName(mp.originGame)}</span>
						</span>
					{/if}
					{#if mp.currentGame}
						<span class="inline-flex items-center gap-1">
							<span class="text-gray-500">現在:</span>
							<span class="font-medium">{getGameName(mp.currentGame)}</span>
						</span>
					{/if}
					{#if mp.level}
						<span class="inline-flex items-center gap-1">
							<span class="text-gray-500">Lv:</span>
							<span class="font-medium">{mp.level}</span>
						</span>
					{/if}
				</div>
				{#if mp.memo}
					<p class="mt-1 text-xs text-gray-600">{mp.memo}</p>
				{/if}
			</div>
		{/if}

		<!-- リボン獲得率 -->
		<div class="mt-2 rounded-lg bg-gray-50 p-2 md:mt-4 md:p-3">
			<div class="flex items-center justify-between">
				<span class="font-medium text-sm">リボン獲得率</span>
				<span class="text-sm font-bold">
					{ribbonProgress.currentCheckedRibbons.length} / {ribbonProgress.allRibbons.length}
					({ribbonPercentage}%)
				</span>
			</div>
			<div class="mt-1 h-2 w-full rounded-full bg-gray-200">
				<div
					class="h-2 rounded-full bg-blue-500 transition-all"
					style="width: {ribbonPercentage}%"
				></div>
			</div>
		</div>
	</div>
{:else}
	<!-- プレースホルダー -->
	<div class="rounded-lg bg-gray-50 p-4 text-center md:p-8">
		<p class="text-gray-500">ポケモンを選択してください</p>
	</div>
{/if}

// components/PokemonDetails.vue
<template>
  <div v-if="pokemon" class="pokemon-details bg-white p-2 md:p-4 rounded-lg shadow">
    <!-- ポケモン基本情報セクション -->
    <div class="flex items-center mb-2 md:mb-4">
      <div class="mr-2 md:mr-4">
        <img :src="pokemon.imageUrl" :alt="pokemon.name" class="w-16 h-16 md:w-24 md:h-24 object-contain" />
      </div>

      <div>
        <h2 class="text-lg md:text-xl font-bold">{{ pokemon.name }}</h2>
        <p class="text-gray-600">#{{ pokemon.number }}</p>

        <!-- タイプ表示 -->
        <div class="flex mt-1 gap-1 md:gap-2">
          <span
            v-for="type in pokemon.types"
            :key="type"
            class="px-2 py-1 text-xs rounded text-white"
            :class="getTypeClass(type)"
          >
            {{ type }}
          </span>
        </div>
      </div>
    </div>

    <!-- マイポケモン追加情報 -->
    <div v-if="store.activeMyPokemon" class="mt-2 md:mt-3 p-2 md:p-3 bg-blue-50 rounded-lg">
      <div class="flex flex-wrap gap-2 text-sm">
        <span v-if="store.activeMyPokemon.nickname" class="inline-flex items-center gap-1">
          <span class="text-gray-500">NN:</span>
          <span class="font-medium">{{ store.activeMyPokemon.nickname }}</span>
        </span>
        <span v-if="store.activeMyPokemon.originGame" class="inline-flex items-center gap-1">
          <span class="text-gray-500">出身:</span>
          <span class="font-medium">{{ getGameName(store.activeMyPokemon.originGame) }}</span>
        </span>
      </div>
      <p v-if="store.activeMyPokemon.memo" class="mt-1 text-xs text-gray-600">
        {{ store.activeMyPokemon.memo }}
      </p>
    </div>

    <!-- マイポケモン登録ボタン（未登録時のみ表示） -->
    <div v-if="isNotRegistered" class="mt-2 md:mt-3">
      <button
        class="w-full px-3 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 text-sm font-medium"
        @click="triggerRegister"
      >
        {{ pokemon?.name }} をマイポケモンに登録
      </button>
    </div>

    <!-- リボン獲得率 -->
    <div class="mt-2 md:mt-4 bg-gray-50 p-2 md:p-3 rounded-lg">
      <div class="flex justify-between items-center">
        <span class="font-medium">リボン獲得率</span>
        <span class="font-bold"
          >{{ store.currentCheckedRibbons.length }} / {{ store.ribbons.length }} ({{ ribbonPercentage }}%)</span
        >
      </div>
      <div class="w-full bg-gray-200 rounded-full h-2 mt-1">
        <div class="bg-blue-500 h-2 rounded-full" :style="`width: ${ribbonPercentage}%`"></div>
      </div>
    </div>
  </div>

  <div v-else class="p-4 md:p-8 text-center bg-gray-50 rounded-lg">
    <p class="text-gray-500">ポケモンを選択してください😊</p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { Pokemon } from '~/types';
import { useRibbonProgressStore } from '~/stores/ribbonProgress';
import { getGameName } from '~/utils/gameNames';

// プロパティ定義
const props = defineProps<{
  pokemon: Pokemon | null;
}>();

const store = useRibbonProgressStore();

/** 選択中のポケモンがマイポケモンに未登録かどうか */
const isNotRegistered = computed(() => {
  if (!props.pokemon) return false;
  return !store.myPokemonList.some((mp) => mp.pokemonId === props.pokemon!.id);
});

/** マイポケモン登録フォームをトリガー */
const triggerRegister = (): void => {
  store.triggerRegisterForm = true;
};

// リボン獲得率の計算（store のリアルタイムデータを使用）
const ribbonPercentage = computed(() => {
  if (!props.pokemon) return 0;
  if (store.ribbons.length === 0) return 0;
  return Math.round((store.currentCheckedRibbons.length / store.ribbons.length) * 100);
});

// ポケモンタイプに応じたCSSクラスを返す
const getTypeClass = (type: string): string => {
  const typeClasses: Record<string, string> = {
    ノーマル: 'bg-gray-400',
    ほのお: 'bg-red-500',
    みず: 'bg-blue-500',
    でんき: 'bg-yellow-400',
    くさ: 'bg-green-500',
    こおり: 'bg-blue-300',
    かくとう: 'bg-red-700',
    どく: 'bg-purple-500',
    じめん: 'bg-yellow-700',
    ひこう: 'bg-blue-400',
    エスパー: 'bg-pink-400',
    むし: 'bg-lime-500',
    いわ: 'bg-yellow-600',
    ゴースト: 'bg-purple-700',
    ドラゴン: 'bg-indigo-600',
    あく: 'bg-gray-700',
    はがね: 'bg-gray-500',
    フェアリー: 'bg-pink-300',
  };

  return typeClasses[type] || 'bg-gray-400';
};
</script>
