// components/MyPokemonPanel.vue
<template>
  <div class="bg-white border rounded-lg shadow-sm mb-4 md:mb-8">
    <!-- ヘッダー（クリックで開閉） -->
    <button
      class="w-full flex justify-between items-center p-3 md:p-4 hover:bg-gray-50"
      @click="isOpen = !isOpen"
    >
      <div class="flex items-center gap-2">
        <h3 class="font-bold text-sm md:text-base">マイポケモン</h3>
        <span class="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded-full">
          {{ store.myPokemonList.length }}
        </span>
      </div>
      <span class="text-gray-400 text-sm">{{ isOpen ? '▲' : '▼' }}</span>
    </button>

    <!-- パネル本体 -->
    <div v-if="isOpen" class="px-3 pb-3 md:px-4 md:pb-4">
      <!-- マイポケモン未登録 & ポケモン未選択 -->
      <div
        v-if="store.myPokemonList.length === 0 && !store.selectedPokemon"
        class="text-center py-4 text-gray-500 text-sm"
      >
        ポケモンを検索・選択して「マイポケモンに登録」してね
      </div>

      <!-- マイポケモン一覧 -->
      <div
        v-if="store.myPokemonList.length > 0"
        class="flex gap-2 overflow-x-auto pb-2 md:grid md:grid-cols-3 lg:grid-cols-4 md:gap-3"
      >
        <div
          v-for="mp in store.myPokemonList"
          :key="mp.id"
          class="flex-shrink-0 w-36 md:w-auto border rounded-lg p-2 cursor-pointer hover:bg-gray-50 transition-colors"
          :class="{ 'ring-2 ring-blue-500 bg-blue-50': store.activeMyPokemonId === mp.id }"
          @click="store.switchMyPokemon(mp.id)"
        >
          <div class="flex items-center gap-2">
            <img
              v-if="getPokemonImage(mp.pokemonId)"
              :src="getPokemonImage(mp.pokemonId)"
              :alt="getDisplayName(mp)"
              class="w-10 h-10 object-contain"
            />
            <div class="flex-1 min-w-0">
              <div class="font-medium text-sm truncate">{{ getDisplayName(mp) }}</div>
              <div class="text-xs text-gray-500 truncate">{{ getGameDisplayName(mp.originGame) }}</div>
              <div class="text-xs text-blue-600">{{ getProgress(mp.id) }}%</div>
            </div>
          </div>
          <!-- 編集・削除ボタン -->
          <div class="flex gap-1 mt-1">
            <button
              class="text-xs text-gray-400 hover:text-blue-500 px-1"
              @click.stop="startEdit(mp)"
            >
              編集
            </button>
            <button
              class="text-xs text-gray-400 hover:text-red-500 px-1"
              @click.stop="confirmRemove(mp.id)"
            >
              削除
            </button>
          </div>
          <!-- 削除確認UI -->
          <div v-if="removingId === mp.id" class="mt-1 p-1.5 bg-red-50 rounded text-xs border border-red-200">
            <p class="text-red-700 mb-1">本当に削除しますか？</p>
            <div class="flex gap-1">
              <button class="px-2 py-0.5 bg-red-500 text-white rounded hover:bg-red-600" @click.stop="executeRemove">削除</button>
              <button class="px-2 py-0.5 bg-gray-200 rounded hover:bg-gray-300" @click.stop="cancelRemove">キャンセル</button>
            </div>
          </div>
        </div>
      </div>

      <!-- 登録ボタン（ポケモン選択中のみ表示） -->
      <div v-if="store.selectedPokemon && !showForm" class="mt-3">
        <button
          class="w-full px-3 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 text-sm"
          @click="openRegisterForm"
        >
          {{ store.selectedPokemon.name }} をマイポケモンに登録
        </button>
      </div>

      <!-- 登録/編集フォーム -->
      <div v-if="showForm" class="mt-3 border rounded-lg p-3 bg-gray-50">
        <h4 class="font-medium text-sm mb-2">
          {{ editingId ? 'マイポケモンを編集' : 'マイポケモンに登録' }}
        </h4>
        <div class="space-y-2">
          <div>
            <label class="block text-xs text-gray-600 mb-0.5">ニックネーム（任意）</label>
            <input
              v-model="form.nickname"
              type="text"
              placeholder="ニックネーム"
              class="w-full px-2 py-1.5 border rounded text-sm"
            />
          </div>
          <div>
            <label class="block text-xs text-gray-600 mb-0.5">出身ゲーム</label>
            <select v-model="form.originGame" class="w-full px-2 py-1.5 border rounded text-sm bg-white">
              <option value="">選択してください</option>
              <option v-for="game in store.games" :key="game.id" :value="game.id">
                {{ game.name }}
              </option>
            </select>
          </div>
          <div>
            <label class="block text-xs text-gray-600 mb-0.5">メモ（任意）</label>
            <textarea
              v-model="form.memo"
              placeholder="メモ"
              rows="2"
              class="w-full px-2 py-1.5 border rounded text-sm"
            ></textarea>
          </div>
          <div class="flex gap-2">
            <button
              class="flex-1 px-3 py-1.5 bg-blue-500 text-white rounded text-sm hover:bg-blue-600"
              @click="submitForm"
            >
              {{ editingId ? '更新' : '登録' }}
            </button>
            <button
              class="px-3 py-1.5 bg-gray-200 rounded text-sm hover:bg-gray-300"
              @click="cancelForm"
            >
              キャンセル
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, watch } from 'vue';
import { useRibbonProgressStore } from '~/stores/ribbonProgress';
import { getGameName } from '~/utils/gameNames';
import type { MyPokemon } from '~/types';

const store = useRibbonProgressStore();

/** パネルの開閉状態（デスクトップはデフォルト開き） */
const isOpen = ref(true);
const showForm = ref(false);
const editingId = ref<string | null>(null);
const removingId = ref<string | null>(null);

const form = reactive({
  nickname: '',
  originGame: '',
  memo: '',
});

/** ポケモンの画像URLを取得 */
const getPokemonImage = (pokemonId: string): string | undefined => {
  const detail = store.pokemonList.find((p) => p.id === pokemonId);
  return detail?.image;
};

/** 表示名（ニックネーム優先、なければポケモン名） */
const getDisplayName = (mp: MyPokemon): string => {
  if (mp.nickname) return mp.nickname;
  const detail = store.pokemonList.find((p) => p.id === mp.pokemonId);
  return detail?.name ?? mp.pokemonId;
};

/** ゲーム表示名 */
const getGameDisplayName = (gameId: string): string => {
  if (!gameId) return '未設定';
  return getGameName(gameId);
};

/** マイポケモンの進捗率を取得 */
const getProgress = (myPokemonId: string): number => {
  if (store.ribbons.length === 0) return 0;
  const checked = store.progress[myPokemonId]?.length ?? 0;
  return Math.round((checked / store.ribbons.length) * 100);
};

/** 登録フォームを開く */
const openRegisterForm = (): void => {
  editingId.value = null;
  form.nickname = '';
  form.originGame = '';
  form.memo = '';
  showForm.value = true;
};

/** 編集フォームを開く */
const startEdit = (mp: MyPokemon): void => {
  editingId.value = mp.id;
  form.nickname = mp.nickname;
  form.originGame = mp.originGame;
  form.memo = mp.memo;
  showForm.value = true;
};

/** フォーム送信 */
const submitForm = (): void => {
  if (editingId.value) {
    // 編集
    store.updateMyPokemon(editingId.value, {
      nickname: form.nickname,
      originGame: form.originGame,
      memo: form.memo,
    });
  } else if (store.selectedPokemon) {
    // 新規登録
    const mp = store.addMyPokemon({
      pokemonId: store.selectedPokemon.id,
      nickname: form.nickname,
      originGame: form.originGame,
      memo: form.memo,
    });
    // 登録後すぐにアクティブにする
    store.switchMyPokemon(mp.id);
  }
  cancelForm();
};

/** フォームをキャンセル */
const cancelForm = (): void => {
  showForm.value = false;
  editingId.value = null;
};

/** 削除確認状態をセット */
const confirmRemove = (id: string): void => {
  removingId.value = id;
};

/** 削除を実行 */
const executeRemove = (): void => {
  if (removingId.value) {
    store.removeMyPokemon(removingId.value);
    removingId.value = null;
  }
};

/** 削除をキャンセル */
const cancelRemove = (): void => {
  removingId.value = null;
};

// triggerRegisterForm を監視して自動でフォームを開く
watch(
  () => store.triggerRegisterForm,
  (val) => {
    if (val) {
      openRegisterForm();
      isOpen.value = true;
      store.triggerRegisterForm = false;
    }
  }
);
</script>

// src/lib/components/tracker/MyPokemonPanel.svelte
<script lang="ts">
	import { ribbonProgress } from '$lib/stores/ribbonProgress.svelte';
	import { getGameName } from '$lib/utils/gameNames';
	import { GAMES } from '$lib/data/games';
	import type { MyPokemon } from '$lib/types';

	/** レベルの最小・最大値定数 */
	const MIN_LEVEL = 1;
	const MAX_LEVEL = 100;

	/** マイポケモン登録・編集フォームデータ型 */
	interface MyPokemonForm {
		nickname: string;
		originGame: string;
		currentGame: string;
		currentGeneration: number;
		level: number;
		isTransferredToHome: boolean;
		memo: string;
	}

	/** パネルの開閉状態 */
	let isOpen = $state(true);
	/** フォーム表示状態 */
	let showForm = $state(false);
	/** 編集中のマイポケモンID（nullは新規登録） */
	let editingId = $state<string | null>(null);
	/** 削除確認中のマイポケモンID */
	let removingId = $state<string | null>(null);

	/** フォームデータ */
	let form = $state<MyPokemonForm>({
		nickname: '',
		originGame: '',
		currentGame: '',
		currentGeneration: 0,
		level: 1,
		isTransferredToHome: false,
		memo: ''
	});

	/** originGameが変わったらcurrentGenerationを自動計算する */
	$effect(() => {
		if (form.originGame) {
			const game = ribbonProgress.allGames.find((g) => g.id === form.originGame);
			if (game) {
				form.currentGeneration = game.generation;
				// currentGameがまだ未設定なら出身ゲームをデフォルトにする
				if (!form.currentGame) {
					form.currentGame = form.originGame;
				}
			}
		}
	});

	/** ポケモンの画像URLを取得する */
	function getPokemonImage(pokemonId: string): string | undefined {
		return ribbonProgress.allPokemon.find((p) => p.id === pokemonId)?.image;
	}

	/** 表示名（ニックネーム優先、なければポケモン名）を取得する */
	function getDisplayName(mp: MyPokemon): string {
		if (mp.nickname) return mp.nickname;
		const detail = ribbonProgress.allPokemon.find((p) => p.id === mp.pokemonId);
		return detail?.name ?? mp.pokemonId;
	}

	/** 進捗率を取得する */
	function getProgress(myPokemonId: string): number {
		if (ribbonProgress.allRibbons.length === 0) return 0;
		const checked = ribbonProgress.progress[myPokemonId]?.length ?? 0;
		return Math.round((checked / ribbonProgress.allRibbons.length) * 100);
	}

	/** フォームを初期状態にリセットする */
	function resetForm(): void {
		form = {
			nickname: '',
			originGame: '',
			currentGame: '',
			currentGeneration: 0,
			level: 1,
			isTransferredToHome: false,
			memo: ''
		};
	}

	/** 新規登録フォームを開く */
	function openRegisterForm(): void {
		editingId = null;
		resetForm();
		showForm = true;
		isOpen = true;
	}

	/** 編集フォームを開く */
	function startEdit(mp: MyPokemon): void {
		editingId = mp.id;
		form = {
			nickname: mp.nickname,
			originGame: mp.originGame,
			currentGame: mp.currentGame,
			currentGeneration: mp.currentGeneration,
			level: mp.level,
			isTransferredToHome: mp.isTransferredToHome,
			memo: mp.memo
		};
		showForm = true;
	}

	/** フォームを送信する */
	function submitForm(): void {
		if (!ribbonProgress.selectedPokemon && !editingId) return;

		if (editingId) {
			// 編集
			ribbonProgress.updateMyPokemon(editingId, {
				nickname: form.nickname,
				originGame: form.originGame,
				currentGame: form.currentGame,
				currentGeneration: form.currentGeneration,
				level: form.level,
				isTransferredToHome: form.isTransferredToHome,
				memo: form.memo
			});
		} else if (ribbonProgress.selectedPokemon) {
			// 新規登録
			const id = ribbonProgress.addMyPokemon({
				pokemonId: ribbonProgress.selectedPokemon.id,
				nickname: form.nickname,
				originGame: form.originGame,
				currentGame: form.currentGame,
				currentGeneration: form.currentGeneration,
				level: form.level,
				isTransferredToHome: form.isTransferredToHome,
				memo: form.memo
			});
			// 登録後すぐにアクティブにする
			ribbonProgress.switchMyPokemon(id);
		}
		cancelForm();
	}

	/** フォームをキャンセルする */
	function cancelForm(): void {
		showForm = false;
		editingId = null;
		resetForm();
	}

	/** 削除確認状態をセットする */
	function confirmRemove(id: string): void {
		removingId = id;
	}

	/** 削除を実行する */
	function executeRemove(): void {
		if (removingId) {
			ribbonProgress.removeMyPokemon(removingId);
			removingId = null;
		}
	}

	/** 削除をキャンセルする */
	function cancelRemove(): void {
		removingId = null;
	}
</script>

<div class="mb-4 rounded-lg border bg-white shadow-sm md:mb-8">
	<!-- ヘッダー（クリックで開閉） -->
	<button
		class="flex w-full items-center justify-between p-3 hover:bg-gray-50 md:p-4"
		onclick={() => (isOpen = !isOpen)}
	>
		<div class="flex items-center gap-2">
			<h3 class="text-sm font-bold md:text-base">マイポケモン</h3>
			<span class="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-500">
				{ribbonProgress.myPokemonList.length}
			</span>
		</div>
		<span class="text-sm text-gray-400">{isOpen ? '▲' : '▼'}</span>
	</button>

	<!-- パネル本体 -->
	{#if isOpen}
		<div class="px-3 pb-3 md:px-4 md:pb-4">
			<!-- マイポケモン未登録かつポケモン未選択 -->
			{#if ribbonProgress.myPokemonList.length === 0 && !ribbonProgress.selectedPokemon}
				<div class="py-4 text-center text-sm text-gray-500">
					ポケモンを検索・選択して「マイポケモンに登録」してください
				</div>
			{/if}

			<!-- マイポケモン一覧 -->
			{#if ribbonProgress.myPokemonList.length > 0}
				<div class="flex gap-2 overflow-x-auto pb-2 md:grid md:grid-cols-3 md:gap-3 lg:grid-cols-4">
					{#each ribbonProgress.myPokemonList as mp (mp.id)}
						<div
							class="w-36 flex-shrink-0 cursor-pointer rounded-lg border p-2 transition-colors hover:bg-gray-50 md:w-auto
								{ribbonProgress.activeMyPokemonId === mp.id ? 'bg-blue-50 ring-2 ring-blue-500' : ''}"
							role="button"
							tabindex="0"
							onclick={() => ribbonProgress.switchMyPokemon(mp.id)}
							onkeydown={(e) => e.key === 'Enter' && ribbonProgress.switchMyPokemon(mp.id)}
						>
							<div class="flex items-center gap-2">
								<!-- ポケモン画像 -->
								{#if getPokemonImage(mp.pokemonId)}
									<img
										src={getPokemonImage(mp.pokemonId)}
										alt={getDisplayName(mp)}
										class="h-10 w-10 object-contain"
									/>
								{:else}
									<div class="h-10 w-10 rounded-full bg-gray-200"></div>
								{/if}
								<div class="min-w-0 flex-1">
									<div class="truncate text-sm font-medium">{getDisplayName(mp)}</div>
									<div class="truncate text-xs text-gray-500">
										{mp.originGame ? getGameName(mp.originGame) : '未設定'}
									</div>
									<div class="text-xs text-blue-600">{getProgress(mp.id)}%</div>
								</div>
							</div>

							<!-- 編集・削除ボタン -->
							<div class="mt-1 flex gap-1">
								<button
									class="px-1 text-xs text-gray-400 hover:text-blue-500"
									onclick={(e) => { e.stopPropagation(); startEdit(mp); }}
								>
									編集
								</button>
								<button
									class="px-1 text-xs text-gray-400 hover:text-red-500"
									onclick={(e) => { e.stopPropagation(); confirmRemove(mp.id); }}
								>
									削除
								</button>
							</div>

							<!-- 削除確認UI -->
							{#if removingId === mp.id}
								<div class="mt-1 rounded border border-red-200 bg-red-50 p-1.5 text-xs">
									<p class="mb-1 text-red-700">本当に削除しますか？</p>
									<div class="flex gap-1">
										<button
											class="rounded bg-red-500 px-2 py-0.5 text-white hover:bg-red-600"
											onclick={(e) => { e.stopPropagation(); executeRemove(); }}
										>
											削除
										</button>
										<button
											class="rounded bg-gray-200 px-2 py-0.5 hover:bg-gray-300"
											onclick={(e) => { e.stopPropagation(); cancelRemove(); }}
										>
											キャンセル
										</button>
									</div>
								</div>
							{/if}
						</div>
					{/each}
				</div>
			{/if}

			<!-- 新規登録ボタン（ポケモン選択中かつフォーム非表示時） -->
			{#if ribbonProgress.selectedPokemon && !showForm}
				<div class="mt-3">
					<button
						class="w-full rounded bg-blue-500 px-3 py-2 text-sm text-white hover:bg-blue-600"
						onclick={openRegisterForm}
					>
						{ribbonProgress.selectedPokemon.name} をマイポケモンに登録
					</button>
				</div>
			{/if}

			<!-- 登録/編集フォーム -->
			{#if showForm}
				<div class="mt-3 rounded-lg border bg-gray-50 p-3">
					<h4 class="mb-2 text-sm font-medium">
						{editingId ? 'マイポケモンを編集' : 'マイポケモンに登録'}
					</h4>
					<div class="space-y-2">
						<!-- ニックネーム -->
						<div>
							<label class="mb-0.5 block text-xs text-gray-600">ニックネーム（任意）</label>
							<input
								type="text"
								bind:value={form.nickname}
								placeholder="ニックネーム"
								class="w-full rounded border px-2 py-1.5 text-sm"
							/>
						</div>

						<!-- 出身ゲーム -->
						<div>
							<label class="mb-0.5 block text-xs text-gray-600">出身ゲーム（必須）</label>
							<select bind:value={form.originGame} class="w-full rounded border bg-white px-2 py-1.5 text-sm">
								<option value="">選択してください</option>
								{#each GAMES as game (game.id)}
									<option value={game.id}>{game.name}</option>
								{/each}
							</select>
						</div>

						<!-- 現在のゲーム -->
						<div>
							<label class="mb-0.5 block text-xs text-gray-600">現在のゲーム（必須）</label>
							<select bind:value={form.currentGame} class="w-full rounded border bg-white px-2 py-1.5 text-sm">
								<option value="">選択してください</option>
								{#each GAMES as game (game.id)}
									<option value={game.id}>{game.name}</option>
								{/each}
							</select>
						</div>

						<!-- レベル -->
						<div>
							<label class="mb-0.5 block text-xs text-gray-600">レベル（{MIN_LEVEL}〜{MAX_LEVEL}）</label>
							<input
								type="number"
								bind:value={form.level}
								min={MIN_LEVEL}
								max={MAX_LEVEL}
								class="w-full rounded border px-2 py-1.5 text-sm"
							/>
						</div>

						<!-- HOME転送済み -->
						<div class="flex items-center gap-2">
							<input
								type="checkbox"
								id="isTransferredToHome"
								bind:checked={form.isTransferredToHome}
								class="h-4 w-4"
							/>
							<label for="isTransferredToHome" class="text-xs text-gray-600">
								Pokemon HOMEに転送済み
							</label>
						</div>

						<!-- メモ -->
						<div>
							<label class="mb-0.5 block text-xs text-gray-600">メモ（任意）</label>
							<textarea
								bind:value={form.memo}
								placeholder="メモ"
								rows={2}
								class="w-full rounded border px-2 py-1.5 text-sm"
							></textarea>
						</div>

						<!-- ボタン -->
						<div class="flex gap-2">
							<button
								class="flex-1 rounded bg-blue-500 px-3 py-1.5 text-sm text-white hover:bg-blue-600
									disabled:cursor-not-allowed disabled:opacity-50"
								disabled={!form.originGame || !form.currentGame}
								onclick={submitForm}
							>
								{editingId ? '更新' : '登録'}
							</button>
							<button
								class="rounded bg-gray-200 px-3 py-1.5 text-sm hover:bg-gray-300"
								onclick={cancelForm}
							>
								キャンセル
							</button>
						</div>
					</div>
				</div>
			{/if}
		</div>
	{/if}
</div>
